### ISSUE TITLE
Switches

### ISSUE THREAD

**Issue by robbrad** [mawinkler/astrolive#2]
How do you get Switches working in the backyard.cfg.yaml ?

I have 

```
    components:
      switch:
        kind: switch
        friendly_name: dragonfly
        update_interval: 30
```

eg you have a method https://github.com/mawinkler/astrolive/blob/main/astrolive/observatory.py#L330

But how do I send the id of the switch to get the data for it from the config file ?

**Comment by mawinkler** [comment]
Just to make sure, a switch component in astrolive is something like a PegasusAstro UPBv2. Astrolive automatically enumerates the number of switches (ports) of your switch and creates an actual home assistant switch and sensor for each port.

A sensor entity can be useful for ports like power, current, dew heater. A switch entity like a USB port or power port to switch a device on or on. Here's an example how it looks like on my lovelace UI:

```
- type: custom:mushroom-entity-card
  entity: switch.astrolive_pegasusastro_upbv2_switch_0
  secondary_info: none
  tap_action:
    action: toggle
    confirmation: true
  hold_action:
    action: none
  double_tap_action:
    action: none
  fill_container: false
  layout: horizontal
  name: QHY 268C (Power)
```

An example for a dew heater on my UI looks like:

```
- align_state: center
  animate: false
  line_width: 2
  font_size: 20
  entities:
    - entity: sensor.astrolive_pegasusastro_upbv2_switch_value_10
      color: white
  hours_to_show: 2
  points_per_hour: 60
  show:
    name: false
    icon: false
    extrema: false
    labels: true
    state: false
  type: custom:mini-graph-card
```

I don't know the dragonfly switch. can this be controlled by ASCOM and did you configure it in ASCOM remote?
